In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('raw_data/q1_2025.csv')

In [4]:
df.head()

,المنطقة,المدينة,المدينة / الحي,الرقم المرجعي للصفقة,تاريخ الصفقة ميلادي,تاريخ الصفقة هجري,تصنيف العقار,عدد العقارات,السعر,المساحة
0,منطقة مكة المكرمه,الطائف,الطائف/ الجودية,27006520.0,2025/01/01,1446/07/01,سكني,1.0,"275,000",760.50
1,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27051687.0,2025/01/01,1446/07/01,سكني,1.0,"523,335",360.00
2,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27038443.0,2025/01/01,1446/07/01,سكني,1.0,"1,000,000",354.42
3,منطقة الرياض,الرياض,الرياض/الزهراء,27048618.0,2025/01/01,1446/07/01,سكني,1.0,"1,800,000",348.75
4,منطقة نجران,شروره,شروره/ الوديعة,27042546.0,2025/01/01,1446/07/01,سكني,1.0,"40,000",625.00

In [6]:
arabic_to_english = {
    "المنطقة": "region_ar",
    "المدينة": "city_ar",
    "الحي / القرية": "district_ar",
    "رقم الصك": "deed_number",
    "تاريخ الصفقة ميلادي": "transaction_date_gregorian",
    "تاريخ الصفقة هجري": "transaction_date_hijri",
    "تصنيف العقار": "property_type_ar",
    "عدد العقارات": "property_count",
    "السعر": "price_sar",
    "المساحة": "area_sqm"
}

property_type_map = {
    "سكني": "Residential",
    "تجاري": "Commercial",
    "زراعي": "Agricultural",
    "صناعي": "Industrial",
    "حكومي": "Government",
    "تعليمي": "Educational",
    "صحي": "Healthcare",
    "متعدد الاستخدام": "Mixed Use"
}

region_map = {
    "منطقة الرياض": "Riyadh Region",
    "منطقة مكة المكرمة": "Makkah Region",
    "منطقة المدينة المنورة": "Madinah Region",
    "المنطقة الشرقية": "Eastern Region",
    "منطقة عسير": "Asir Region",
    "منطقة تبوك": "Tabuk Region",
    "منطقة حائل": "Hail Region",
    "منطقة القصيم": "Qassim Region",
    "منطقة جازان": "Jazan Region",
    "منطقة نجران": "Najran Region",
    "منطقة الباحة": "Al Baha Region",
    "منطقة الجوف": "Al Jouf Region",
    "منطقة الحدود الشمالية": "Northern Borders Region"
}

city_map = {
    "الرياض": "Riyadh",
    "جدة": "Jeddah",
    "مكة": "Makkah",
    "المدينة المنورة": "Madinah",
    "الطائف": "Taif",
    "أبها": "Abha",
    "خميس مشيط": "Khamis Mushait",
    "الدمام": "Dammam",
    "الخبر": "Khobar",
    "بريدة": "Buraydah",
    "تبوك": "Tabuk",
    "حائل": "Hail",
    "جازان": "Jazan",
    "نجران": "Najran",
    "سكاكا": "Sakaka",
    "عرعر": "Arar",
    "بيشة": "Bisha",
    "الأفلاج": "Al Aflaj",
    "الطائف/ الجودية": "Taif / Al Jawdiyah"  # not always needed, just example
}

In [11]:
files = {
    "Q1": "raw_data/q1_2025.csv",
    "Q2": "raw_data/q2_2025.csv",
    "Q3": "raw_data/q3_2025.csv",
    "Q4": "raw_data/q4_2025.csv"
}

In [12]:
all_dfs = []

In [13]:
for quarter, file_path in files.items():
    df = pd.read_csv(file_path, encoding="utf-8-sig")
    df.columns = df.columns.str.strip()
    df = df.rename(columns=arabic_to_english)
    df["quarter"] = quarter
    all_dfs.append(df)

df_all = pd.concat(all_dfs, ignore_index=True)

In [14]:
# Create English helper columns
df_all["property_type_en"] = df_all["property_type_ar"].map(property_type_map)
df_all["region_en"] = df_all["region_ar"].map(region_map)
df_all["city_en"] = df_all["city_ar"].map(city_map)

In [15]:
print(df_all.head())

           region_ar city_ar             المدينة / الحي  الرقم المرجعي للصفقة  \
0  منطقة مكة المكرمه  الطائف           الطائف/ الجودية             27006520.0
1  منطقة مكة المكرمه  الطائف  الطائف/ الشهداء الجنوبية             27051687.0
2  منطقة مكة المكرمه  الطائف  الطائف/ الشهداء الجنوبية             27038443.0
3       منطقة الرياض  الرياض             الرياض/الزهراء            27048618.0
4        منطقة نجران   شروره            شروره/ الوديعة             27042546.0

  transaction_date_gregorian transaction_date_hijri property_type_ar  \
0                 2025/01/01             1446/07/01             سكني
1                 2025/01/01             1446/07/01             سكني
2                 2025/01/01             1446/07/01             سكني
3                 2025/01/01             1446/07/01             سكني
4                 2025/01/01             1446/07/01             سكني

   property_count  price_sar area_sqm quarter property_type_en      region_en  \
0             1.0    275,000   760.50      Q1      Residential            NaN
1             1.0    523,335   360.00      Q1      Residential            NaN
2             1.0  1,000,000   354.42      Q1      Residential            NaN
3             1.0  1,800,000   348.75      Q1      Residential  Riyadh Region
4             1.0     40,000   625.00      Q1      Residential  Najran Region

  city_en
0    Taif
1    Taif
2    Taif
3  Riyadh
4     NaN

In [16]:
df_all.head()

,region_ar,city_ar,المدينة / الحي,الرقم المرجعي للصفقة,transaction_date_gregorian,transaction_date_hijri,property_type_ar,property_count,price_sar,area_sqm,quarter,property_type_en,region_en,city_en
0,منطقة مكة المكرمه,الطائف,الطائف/ الجودية,27006520.0,2025/01/01,1446/07/01,سكني,1.0,"275,000",760.50,Q1,Residential,NaN,Taif
1,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27051687.0,2025/01/01,1446/07/01,سكني,1.0,"523,335",360.00,Q1,Residential,NaN,Taif
2,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27038443.0,2025/01/01,1446/07/01,سكني,1.0,"1,000,000",354.42,Q1,Residential,NaN,Taif
3,منطقة الرياض,الرياض,الرياض/الزهراء,27048618.0,2025/01/01,1446/07/01,سكني,1.0,"1,800,000",348.75,Q1,Residential,Riyadh Region,Riyadh
4,منطقة نجران,شروره,شروره/ الوديعة,27042546.0,2025/01/01,1446/07/01,سكني,1.0,"40,000",625.00,Q1,Residential,Najran Region,NaN

In [17]:
df_all.tail()

,region_ar,city_ar,المدينة / الحي,الرقم المرجعي للصفقة,transaction_date_gregorian,transaction_date_hijri,property_type_ar,property_count,price_sar,area_sqm,quarter,property_type_en,region_en,city_en
201552,منطقة عسير,ابها,ابها/ المسك,34236006.0,2025/12/31,1447/07/11,سكني,1.0,"785,610",611.37,Q4,Residential,Asir Region,NaN
201553,منطقة الشرقية,الدمام,الدمام/ البيضاء,34234601.0,2025/12/31,1447/07/11,سكني,1.0,"5,493,125","9,987.50",Q4,Residential,NaN,Dammam
201554,منطقة الشرقية,الدمام,الدمام/ البيضاء,34235101.0,2025/12/31,1447/07/11,سكني,1.0,"5,490,100","9,982.00",Q4,Residential,NaN,Dammam
201555,منطقة الشرقية,الدمام,الدمام/ البيضاء,34224565.0,2025/12/31,1447/07/11,سكني,1.0,"1,869,350","2,670.50",Q4,Residential,NaN,Dammam
201556,منطقة الشرقية,الدمام,الدمام/ البيضاء,34223666.0,2025/12/31,1447/07/11,سكني,1.0,"1,901,900","2,717.00",Q4,Residential,NaN,Dammam

In [18]:
print(df_all[df_all["city_en"].isna()]["city_ar"].dropna().unique())
print(df_all[df_all["region_en"].isna()]["region_ar"].dropna().unique())
print(df_all[df_all["property_type_en"].isna()]["property_type_ar"].dropna().unique())

['شروره' 'حوطة بني تميم' 'الدلم' 'الافلاج' 'بيشه' 'رجال المع' 'عفيف'
 'بلجرشي' 'مرات' 'الليث' 'الشقيق' 'طريب' 'جده' 'النعيريه' 'ضرماء'
 'مكة المكرمة' 'المهد' 'رماح' 'السليل' 'بريده' 'تثليت' 'الدوادمي' 'يدمه'
 'الارطاويه' 'العقيق' 'الحناكية' 'رنيه' 'طبرجل' 'الباحه' 'الحائط' 'البرك'
 'الروضة' 'الحجره' 'بحره' 'رابغ' 'القويعيه' 'القصب' 'الشنان' 'الشملى'
 'الدرعيه' 'القطيف' 'حفر الباطن' 'خليص' 'بارق' 'تربه' 'وادي الفرع' 'جيزان'
 'طريف' 'الشماسيه' 'الهفوف' 'ابو عريش' 'الجفر' 'عنيزه' 'صبياء' 'الزلفي'
 'البكيريه' 'ابقيق' 'الخبراء' 'المخواة' 'الرس' 'رياض الخبراء' 'سراة عبيده'
 'المذنب' 'البدائع' 'ابها' 'المزاحميه' 'صامطه' 'الخرج' 'بقعاء' 'حريملاء'
 'الجبيل' 'الاحساء' 'الظهران' 'القنفذه' 'احد رفيده' 'الخفجي' 'عيون الجوى'
 'ضمد' 'المجمعه' 'شقراء' 'تيماء' 'بيش' 'القريات' 'الغاط' 'محايل عسير'
 'الخرمه' 'الكهفه' 'موقق' 'الدرب' 'ضريه' 'الاسياح' 'ثادق' 'املج' 'الغزاله'
 'دومة الجندل' 'الرين' 'الارطاوي' 'العيدابي' 'رفحاء' 'الحريق' 'العيون'
 'عقلة الصقور' 'قرية العليا' 'وادي الدواسر' 'ثار' 'حبونا' 'قلوه'
 'العويقيله' 'المويه' 'جلاجل' 'الجموم' 'ضباء' 'احد المسارحه' 'باللسمر'
 'ينبع' 'ظهران الجنوب' 'فرسان' 'قبه' 'المجارده' 'سميراء' 'الكامل'
 'القواره' 'النماص' 'البشائر' 'بلقرن' 'المندق' 'النبهانيه' 'لينه' 'حقل'
 'السليمي' 'العرضيه الجنوبيه' 'بحر ابو سكينه' 'ميسان' 'رأس تنوره' 'القرى'
 'العارضه' 'الدائر' 'العرضيه الشماليه' 'الريث' 'هروب' 'بدر الجنوب'
 'بني حسن' 'الحرث' 'فيفا' 'الطوال' 'فزعة غامد الزناد' 'العلا' 'البصر'
 'ملهم' 'خيبر' 'عرقه' 'الشعبه']
['منطقة مكة المكرمه' 'منطقة الشرقية' 'منطقة المدينة المنوره']
['سكني تجاري']

In [19]:
print(df_all["property_type_ar"].dropna().unique())
print(df_all["region_ar"].dropna().unique())
print(df_all["city_ar"].dropna().unique()[:30])

['سكني' 'تجاري' 'زراعي' 'سكني تجاري']
['منطقة مكة المكرمه' 'منطقة الرياض' 'منطقة نجران' 'منطقة عسير'
 'منطقة الباحة' 'منطقة الشرقية' 'منطقة المدينة المنوره' 'منطقة جازان'
 'منطقة تبوك' 'منطقة الجوف' 'منطقة القصيم' 'منطقة حائل'
 'منطقة الحدود الشمالية']
['الطائف' 'الرياض' 'شروره' 'حوطة بني تميم' 'الدلم' 'الافلاج' 'بيشه'
 'رجال المع' 'عفيف' 'بلجرشي' 'الدمام' 'مرات' 'الليث' 'المدينة المنورة'
 'الشقيق' 'طريب' 'جده' 'النعيريه' 'ضرماء' 'مكة المكرمة' 'المهد' 'تبوك'
 'سكاكا' 'رماح' 'الخبر' 'السليل' 'بريده' 'تثليت' 'الدوادمي' 'يدمه']

In [20]:
property_type_map = {
    "سكني": "Residential",
    "تجاري": "Commercial",
    "زراعي": "Agricultural",
    "صناعي": "Industrial"
}

df_all["property_type_en"] = df_all["property_type_ar"].map(property_type_map)

In [21]:
region_map = {
    "منطقة الرياض": "Riyadh Region",
    "منطقة مكة المكرمة": "Makkah Region",
    "منطقة المدينة المنورة": "Madinah Region",
    "المنطقة الشرقية": "Eastern Region",
    "منطقة عسير": "Asir Region",
    "منطقة تبوك": "Tabuk Region",
    "منطقة حائل": "Hail Region",
    "منطقة القصيم": "Qassim Region",
    "منطقة جازان": "Jazan Region",
    "منطقة نجران": "Najran Region",
    "منطقة الباحة": "Al Baha Region",
    "منطقة الجوف": "Al Jouf Region",
    "منطقة الحدود الشمالية": "Northern Borders Region"
}

df_all["region_en"] = df_all["region_ar"].map(region_map)

In [22]:
city_map = {
    "الرياض": "Riyadh",
    "جدة": "Jeddah",
    "مكة المكرمة": "Makkah",
    "مكة": "Makkah",
    "المدينة المنورة": "Madinah",
    "الدمام": "Dammam",
    "الخبر": "Khobar",
    "الطائف": "Taif",
    "بريدة": "Buraydah",
    "أبها": "Abha",
    "تبوك": "Tabuk",
    "حائل": "Hail",
    "نجران": "Najran",
    "جازان": "Jazan",
    "سكاكا": "Sakaka",
    "عرعر": "Arar"
}

df_all["city_en"] = df_all["city_ar"].map(city_map)

In [23]:
df_all["city_final"] = df_all["city_en"].fillna(df_all["city_ar"])

In [24]:
df_all["price_sar"] = df_all["price_sar"].astype(str).str.replace(",", "", regex=False)
df_all["price_sar"] = pd.to_numeric(df_all["price_sar"], errors="coerce")

df_all["area_sqm"] = pd.to_numeric(df_all["area_sqm"], errors="coerce")

In [25]:
df_all["price_per_sqm"] = df_all["price_sar"] / df_all["area_sqm"]

In [26]:
df_all = df_all[df_all["area_sqm"] > 0]
df_all = df_all[df_all["price_sar"] > 0]

In [27]:
df_all.head()

,region_ar,city_ar,المدينة / الحي,الرقم المرجعي للصفقة,transaction_date_gregorian,transaction_date_hijri,property_type_ar,property_count,price_sar,area_sqm,quarter,property_type_en,region_en,city_en,city_final,price_per_sqm
0,منطقة مكة المكرمه,الطائف,الطائف/ الجودية,27006520.0,2025/01/01,1446/07/01,سكني,1.0,275000.0,760.50,Q1,Residential,NaN,Taif,Taif,361.604208
1,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27051687.0,2025/01/01,1446/07/01,سكني,1.0,523335.0,360.00,Q1,Residential,NaN,Taif,Taif,1453.708333
2,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27038443.0,2025/01/01,1446/07/01,سكني,1.0,1000000.0,354.42,Q1,Residential,NaN,Taif,Taif,2821.511201
3,منطقة الرياض,الرياض,الرياض/الزهراء,27048618.0,2025/01/01,1446/07/01,سكني,1.0,1800000.0,348.75,Q1,Residential,Riyadh Region,Riyadh,Riyadh,5161.290323
4,منطقة نجران,شروره,شروره/ الوديعة,27042546.0,2025/01/01,1446/07/01,سكني,1.0,40000.0,625.00,Q1,Residential,Najran Region,NaN,شروره,64.000000

In [28]:
df_all.describe()

,الرقم المرجعي للصفقة,property_count,price_sar,area_sqm,price_per_sqm
count,1.833050e+05,183305.000000,1.833050e+05,183305.000000,183305.000000
mean,3.023102e+07,1.002275,6.355196e+05,448.906670,1898.153671
std,2.157346e+06,0.060189,9.467854e+05,228.589521,2634.713422
min,2.486826e+07,1.000000,5.000000e+03,0.330000,5.020786
25%,2.823529e+07,1.000000,1.600000e+05,268.820000,356.294537
50%,3.006318e+07,1.000000,4.200000e+05,426.550000,1117.914460
75%,3.212868e+07,1.000000,7.700000e+05,625.000000,2688.172043
max,3.423832e+07,8.000000,4.926189e+07,999.980000,197036.569987

In [29]:
df_all["city_final"].value_counts().head(10)

city_final
Riyadh     31562
جده        30119
Madinah    10446
Makkah      9329
بريده       5719
Dammam      5248
Khobar      5139
Hail        5052
الهفوف      4896
Taif        4890
Name: count, dtype: int64

In [30]:
df_all[df_all["region_en"].isna()]["region_ar"].unique()

array(['منطقة مكة المكرمه', 'منطقة الشرقية', 'منطقة المدينة المنوره'],
      dtype=object)

In [31]:
df_all["city_final"] = df_all["city_en"].fillna(df_all["city_ar"])

In [32]:
df_all["city_clean"] = df_all["city_final"]

In [33]:
df_all["price_sar"].sum()

116493922343.0

In [34]:
len(df_all)

183305

In [35]:
df_all["price_per_sqm"].mean()

1898.1536713033588

In [36]:
df_all.groupby("city_final").size().sort_values(ascending=False).head(10)

city_final
Riyadh     31562
جده        30119
Madinah    10446
Makkah      9329
بريده       5719
Dammam      5248
Khobar      5139
Hail        5052
الهفوف      4896
Taif        4890
dtype: int64

In [37]:
df_all.groupby("city_final")["price_sar"].sum().sort_values(ascending=False).head(10)

city_final
Riyadh     3.175761e+10
جده        3.053138e+10
Makkah     8.992397e+09
Madinah    7.183107e+09
Khobar     4.600980e+09
Dammam     4.543123e+09
Taif       2.485957e+09
الهفوف     2.358435e+09
Tabuk      1.969803e+09
Hail       1.801363e+09
Name: price_sar, dtype: float64

In [85]:
df_all.groupby("city_final")["price_per_sqm"].mean().sort_values(ascending=False).head(10)

city_final
املج       19088.127009
عرقه        8546.141944
الدرعيه     3851.068140
Riyadh      3426.407905
Khobar      3175.115778
جده         3107.049662
Makkah      2854.070002
الظهران     2646.508731
Dammam      2623.263727
القطيف      2205.066120
Name: price_per_sqm, dtype: float64

In [40]:
df_all.groupby("property_type_en")["price_sar"].agg(["count","mean"])

                   count          mean
property_type_en
Agricultural         246  3.646171e+05
Commercial          9537  1.278440e+06
Residential       173522  6.005679e+05

In [41]:
df_all.groupby("quarter")["price_sar"].sum()

quarter
Q1    3.919610e+10
Q2    2.453178e+10
Q3    2.730390e+10
Q4    2.546214e+10
Name: price_sar, dtype: float64

In [42]:
df_all.groupby("quarter").size()

quarter
Q1    59340
Q2    38927
Q3    44693
Q4    40345
dtype: int64

In [43]:
q99 = df_all["price_per_sqm"].quantile(0.99)
df_clean = df_all[df_all["price_per_sqm"] < q99]

In [88]:
df_clean = df_all[df_all["price_per_sqm"] < df_all["price_per_sqm"].quantile(0.99)]

top_cities = df_clean.groupby("city_final").size().sort_values(ascending=False).head(10)
top_value = df_clean.groupby("city_final")["price_sar"].sum().sort_values(ascending=False).head(10)
top_price = df_clean.groupby("city_final")["price_per_sqm"].mean().sort_values(ascending=False).head(10)

In [86]:
df_clean

,region_ar,city_ar,المدينة / الحي,الرقم المرجعي للصفقة,transaction_date_gregorian,transaction_date_hijri,property_type_ar,property_count,price_sar,area_sqm,quarter,property_type_en,region_en,city_en,city_final,price_per_sqm,city_clean
0,منطقة مكة المكرمه,الطائف,الطائف/ الجودية,27006520.0,2025/01/01,1446/07/01,سكني,1.0,275000.0,760.50,Q1,Residential,NaN,Taif,Taif,361.604208,Taif
1,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27051687.0,2025/01/01,1446/07/01,سكني,1.0,523335.0,360.00,Q1,Residential,NaN,Taif,Taif,1453.708333,Taif
2,منطقة مكة المكرمه,الطائف,الطائف/ الشهداء الجنوبية,27038443.0,2025/01/01,1446/07/01,سكني,1.0,1000000.0,354.42,Q1,Residential,NaN,Taif,Taif,2821.511201,Taif
3,منطقة الرياض,الرياض,الرياض/الزهراء,27048618.0,2025/01/01,1446/07/01,سكني,1.0,1800000.0,348.75,Q1,Residential,Riyadh Region,Riyadh,Riyadh,5161.290323,Riyadh
4,منطقة نجران,شروره,شروره/ الوديعة,27042546.0,2025/01/01,1446/07/01,سكني,1.0,40000.0,625.00,Q1,Residential,Najran Region,NaN,شروره,64.000000,شروره
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201547,منطقة مكة المكرمه,الطائف,الطائف/ الغمير,34219355.0,2025/12/31,1447/07/11,سكني,1.0,332507.0,325.50,Q4,Residential,NaN,Taif,Taif,1021.526882,Taif
201548,منطقة مكة المكرمه,الطائف,الطائف/ الغمير,34219537.0,2025/12/31,1447/07/11,سكني,1.0,332507.0,325.50,Q4,Residential,NaN,Taif,Taif,1021.526882,Taif
201550,منطقة الرياض,الزلفي,الزلفي/ الفيصليه,34219356.0,2025/12/31,1447/07/11,سكني,1.0,20000.0,123.19,Q4,Residential,Riyadh Region,NaN,الزلفي,162.350840,Zulfi
201551,منطقة عسير,ابها,ابها/ المسك,34236188.0,2025/12/31,1447/07/11,سكني,1.0,750000.0,600.00,Q4,Residential,Asir Region,NaN,ابها,1250.000000,Abha
201552,منطقة عسير,ابها,ابها/ المسك,34236006.0,2025/12/31,1447/07/11,سكني,1.0,785610.0,611.37,Q4,Residential,Asir Region,NaN,ابها,1284.999264,Abha

In [74]:
top_value

city_clean
Jeddah     2.879479e+10
Riyadh     2.812855e+10
Makkah     7.747234e+09
Madinah    6.670026e+09
Dammam     4.489033e+09
Khobar     4.260158e+09
Taif       2.468972e+09
Hofuf      2.355835e+09
Tabuk      1.955303e+09
Hail       1.800333e+09
Name: price_sar, dtype: float64

In [89]:

top_price

city_final
عرقه       8546.141944
الدرعيه    3425.459297
Riyadh     3023.484338
جده        2965.326923
Khobar     2898.182325
الظهران    2646.508731
Dammam     2582.109634
Makkah     2355.194209
القطيف     2205.066120
الاحساء    1799.178530
Name: price_per_sqm, dtype: float64

In [49]:
df_clean["city_clean"] = df_clean["city_en"].fillna(df_clean["city_ar"])

C:\Users\skill\AppData\Local\Temp\ipykernel_13896\2243564557.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["city_clean"] = df_clean["city_en"].fillna(df_clean["city_ar"])

In [57]:
df_clean["city_clean"]

0             Taif
1             Taif
2             Taif
3           Riyadh
4         Sharurah
            ...
201547        Taif
201548        Taif
201550       Zulfi
201551        Abha
201552        Abha
Name: city_clean, Length: 181353, dtype: object

In [73]:
city_fix = {
    "جدة": "Jeddah",
    "بريدة": "Buraydah",
    "ابها": "Abha",
    "القطيف": "Qatif",
    "الأحساء": "Al Ahsa",
    "الدرعية": "Diriyah",
    "عرقة": "Irqah",
    "شروره": "Sharurah",
    "الزلفي": "Zulfi",
    "جده": "Jeddah",
    "بريده": "Buraydah",
    "الطائف/ الجودية": "Taif / Al Jawdiyah",
    "الهفوف": "Hofuf",
    "عرقه": "Irqah",
    "الدرعيه": "Diriyah",
    "الظهران": "Dhahran",
    "القطيف": "Qatif",
    "الاحساء": "Al Ahsa",
    "جده": "Jeddah",

}

df_clean["city_clean"] = df_clean["city_clean"].replace(city_fix)

C:\Users\skill\AppData\Local\Temp\ipykernel_13896\3332909970.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["city_clean"] = df_clean["city_clean"].replace(city_fix)

In [90]:
top_value = df_clean.groupby("city_clean")["price_sar"].sum().sort_values(ascending=False).head(10)

In [91]:
city_counts = df_clean["city_clean"].value_counts()

valid_cities = city_counts[city_counts > 1000].index

top_price_clean = (
    df_clean[df_clean["city_clean"].isin(valid_cities)]
    .groupby("city_clean")["price_per_sqm"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

In [93]:
valid_cities

Index(['Riyadh', 'جده', 'Madinah', 'Makkah', 'بريده', 'Dammam', 'Hail',
       'Khobar', 'الهفوف', 'Taif', 'حفر الباطن', 'Tabuk', 'الخرج', 'خميس مشيط',
       'الجبيل', 'ابها', 'Najran', 'Arar', 'جيزان', 'الجفر', 'بقعاء', 'المذنب',
       'عنيزه', 'القطيف', 'Sakaka', 'المجمعه', 'الخفجي', 'الدوادمي', 'عفيف',
       'الزلفي'],
      dtype='object', name='city_clean')

In [83]:
city_fix = {
    "جده": "Jeddah",
    "بريده": "Buraydah",
    "الهفوف": "Hofuf",
    "الباطن": "Al Batin",
    "حفر الباطن": "Hafar Al Batin",
    "خميس مشيط": "Khamis Mushait",
    "الخرج": "Al Kharj",
    "ابها": "Abha",
    "الجبيل": "Jubail",
    "المذنب": "Al Muzayri",
    "بقعاء" : "Buqaa",
    "الجفر": "Al Jafr",
    "جيزان": "Jazan",
    'عنيزه': 'Anizah',
    'القطيف': 'Qatif',
    'المجمعه': 'Al Makhad',
    'الخفجي': 'Al Kharj',
    'الدوادمي': 'Al Dawadmi',
    'عفيف': 'Afif',
    'الزلفي': 'Zulfi'
}

df_clean["city_clean"] = df_clean["city_clean"].replace(city_fix)

C:\Users\skill\AppData\Local\Temp\ipykernel_13896\4211687543.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["city_clean"] = df_clean["city_clean"].replace(city_fix)

In [94]:
valid_cities

Index(['Riyadh', 'جده', 'Madinah', 'Makkah', 'بريده', 'Dammam', 'Hail',
       'Khobar', 'الهفوف', 'Taif', 'حفر الباطن', 'Tabuk', 'الخرج', 'خميس مشيط',
       'الجبيل', 'ابها', 'Najran', 'Arar', 'جيزان', 'الجفر', 'بقعاء', 'المذنب',
       'عنيزه', 'القطيف', 'Sakaka', 'المجمعه', 'الخفجي', 'الدوادمي', 'عفيف',
       'الزلفي'],
      dtype='object', name='city_clean')

In [95]:
df_clean[df_clean["city_clean"].str.contains(r'[ء-ي]', na=False)]["city_clean"].unique()

array(['شروره', 'حوطة بني تميم', 'الدلم', 'الافلاج', 'بيشه', 'رجال المع',
       'عفيف', 'بلجرشي', 'مرات', 'الليث', 'الشقيق', 'طريب', 'جده',
       'النعيريه', 'ضرماء', 'رماح', 'السليل', 'بريده', 'تثليت',
       'الدوادمي', 'يدمه', 'العقيق', 'الحناكية', 'رنيه', 'طبرجل',
       'الباحه', 'الحائط', 'الروضة', 'الحجره', 'بحره', 'رابغ', 'القويعيه',
       'الشنان', 'الشملى', 'الدرعيه', 'المهد', 'القطيف', 'خليص',
       'حفر الباطن', 'تربه', 'جيزان', 'طريف', 'الشماسيه', 'الهفوف',
       'خميس مشيط', 'ابو عريش', 'الجفر', 'عنيزه', 'الزلفي', 'صبياء',
       'البكيريه', 'ابقيق', 'المخواة', 'رياض الخبراء', 'سراة عبيده',
       'المذنب', 'البدائع', 'ابها', 'صامطه', 'الخرج', 'بقعاء', 'حريملاء',
       'الاحساء', 'الظهران', 'القنفذه', 'احد رفيده', 'الخفجي',
       'عيون الجوى', 'ضمد', 'المجمعه', 'شقراء', 'تيماء', 'بيش', 'الخبراء',
       'الغاط', 'الرس', 'محايل عسير', 'الخرمه', 'الكهفه', 'موقق', 'الدرب',
       'ضريه', 'الاسياح', 'ثادق', 'الغزاله', 'الرين', 'وادي الفرع',
       'الجبيل', 'الارطاوي', 'العيدابي', 'رفحاء', 'الحريق', 'القريات',
       'العيون', 'دومة الجندل', 'عقلة الصقور', 'البرك', 'قرية العليا',
       'القصب', 'ثار', 'حبونا', 'قلوه', 'الارطاويه', 'العويقيله',
       'المويه', 'بارق', 'جلاجل', 'المزاحميه', 'ضباء', 'احد المسارحه',
       'وادي الدواسر', 'باللسمر', 'ينبع', 'ظهران الجنوب', 'فرسان',
       'الجموم', 'المجارده', 'سميراء', 'الكامل', 'القواره', 'النماص',
       'البشائر', 'بلقرن', 'النبهانيه', 'قبه', 'لينه', 'حقل', 'السليمي',
       'العرضيه الجنوبيه', 'بحر ابو سكينه', 'ميسان', 'رأس تنوره', 'القرى',
       'العارضه', 'الدائر', 'العرضيه الشماليه', 'الريث', 'هروب',
       'بدر الجنوب', 'المندق', 'الحرث', 'الطوال', 'فزعة غامد الزناد',
       'العلا', 'خيبر', 'عرقه', 'املج', 'الشعبه'], dtype=object)

In [96]:
df_clean.loc[:, "city_clean"] = df_clean["city_clean"].replace(city_fix)

In [97]:
df_clean["city_clean"] = df_clean["city_clean"].str.strip()

C:\Users\skill\AppData\Local\Temp\ipykernel_13896\1820223147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["city_clean"] = df_clean["city_clean"].str.strip()

In [98]:
df_clean["city_clean"] = df_clean["city_clean"].str.replace("ال", "", regex=False)

C:\Users\skill\AppData\Local\Temp\ipykernel_13896\2922088663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean["city_clean"] = df_clean["city_clean"].str.replace("ال", "", regex=False)

In [103]:
unmapped = df_clean[df_clean["city_clean"].str.contains(r'[ء-ي]', na=False)]["city_clean"].value_counts()
print(unmapped.head(20))

city_clean
بدائع         895
نعيريه        833
قريات         821
بيشه          678
رس            669
رياض خبراء    663
افلاج         644
قنفذه         630
قويعيه        617
تثليت         571
طريب          554
ابقيق         532
صبياء         525
غزه           524
خليص          508
بكيريه        501
موقق          491
حريملاء       470
احساء         465
احد رفيده     462
Name: count, dtype: int64

In [100]:
city_fix_2 = {
    "ابو عريش": "Abu Arish",
    "البدائع": "Al Badai",
    "شقراء": "Shaqra",
    "القويعية": "Al Quwayiyah",
    "رابغ": "Rabigh",
    "بيش": "Bish",
    "بيشة": "Bisha",
    "الرس": "Ar Rass",
    "رياض الخبراء": "Riyadh Al Khabra",
    "تربه": "Turbah",
    "الافلاج": "Al Aflaj",
    "طبرجل": "Tabarjal",
    "رفحا": "Rafha",
    "محايل عسير": "Muhayil Asir",
    "القريات": "Al Qurayyat",
    "تثليث": "Tathlith",
    "طريف": "Turaif",
    "ابها": "Abha",
    "صبيا": "Sabya"
}

In [101]:
df_clean = df_clean.copy()
df_clean.loc[:, "city_clean"] = df_clean["city_clean"].astype(str).str.strip()
df_clean.loc[:, "city_clean"] = df_clean["city_clean"].replace(city_fix_2)

In [102]:
unmapped = df_clean[df_clean["city_clean"].str.contains(r'[ء-ي]', na=False)]["city_clean"].value_counts()
print(unmapped.head(20))

city_clean
بدائع         895
نعيريه        833
قريات         821
بيشه          678
رس            669
رياض خبراء    663
افلاج         644
قنفذه         630
قويعيه        617
تثليت         571
طريب          554
ابقيق         532
صبياء         525
غزه           524
خليص          508
بكيريه        501
موقق          491
حريملاء       470
احساء         465
احد رفيده     462
Name: count, dtype: int64

In [104]:
unmapped = df_clean[df_clean["city_clean"].str.contains(r'[ء-ي]', na=False)]["city_clean"].value_counts()
print(unmapped[unmapped >= 200])

city_clean
بدائع            895
نعيريه           833
قريات            821
بيشه             678
رس               669
رياض خبراء       663
افلاج            644
قنفذه            630
قويعيه           617
تثليت            571
طريب             554
ابقيق            532
صبياء            525
غزه              524
خليص             508
بكيريه           501
موقق             491
حريملاء          470
احساء            465
احد رفيده        462
رماح             460
حناكية           443
دومة جندل        383
روضة             379
رفحاء            368
خبراء            367
وادي فرع         367
دلم              366
شنان             362
وادي دواسر       335
مزاحميه          324
قرية عليا        320
ضرماء            319
بحره             316
مرات             312
ثادق             296
غاط              288
درعيه            286
ينبع             284
باحه             278
تيماء            270
شروره            264
شماسيه           261
بلجرشي           260
مخواة            254
حوطة بني تميم    250
رنيه             233
صامطه            225
عيون             222
خرمه             221
مهد              214
برك              209
سليمي            200
Name: count, dtype: int64

In [105]:
top_cities = df_clean.groupby("city_clean").size().sort_values(ascending=False).head(10)
top_value = df_clean.groupby("city_clean")["price_sar"].sum().sort_values(ascending=False).head(10)

city_counts = df_clean["city_clean"].value_counts()
valid_cities = city_counts[city_counts > 1000].index

top_price = (
    df_clean[df_clean["city_clean"].isin(valid_cities)]
    .groupby("city_clean")["price_per_sqm"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(top_cities)
print(top_value)
print(top_price)

city_clean
Riyadh      30527
Jeddah      29789
Madinah     10340
Makkah       9085
Buraydah     5701
Dammam       5235
Hail         5050
Khobar       5007
Hofuf        4892
Taif         4884
dtype: int64
city_clean
Jeddah     2.879479e+10
Riyadh     2.812855e+10
Makkah     7.747234e+09
Madinah    6.670026e+09
Dammam     4.489033e+09
Khobar     4.260158e+09
Taif       2.468972e+09
Hofuf      2.355835e+09
Tabuk      1.955303e+09
Hail       1.800333e+09
Name: price_sar, dtype: float64
city_clean
Riyadh            3023.484338
Jeddah            2965.326923
Khobar            2898.182325
Dammam            2582.109634
Makkah            2355.194209
Qatif             2205.066120
Madinah           1759.142577
Abha              1550.508561
Jubail            1466.625571
Khamis Mushait    1456.247430
Name: price_per_sqm, dtype: float64

In [106]:
top_cities

city_clean
Riyadh      30527
Jeddah      29789
Madinah     10340
Makkah       9085
Buraydah     5701
Dammam       5235
Hail         5050
Khobar       5007
Hofuf        4892
Taif         4884
dtype: int64

In [107]:
top_value

city_clean
Jeddah     2.879479e+10
Riyadh     2.812855e+10
Makkah     7.747234e+09
Madinah    6.670026e+09
Dammam     4.489033e+09
Khobar     4.260158e+09
Taif       2.468972e+09
Hofuf      2.355835e+09
Tabuk      1.955303e+09
Hail       1.800333e+09
Name: price_sar, dtype: float64

In [108]:
top_price

city_clean
Riyadh            3023.484338
Jeddah            2965.326923
Khobar            2898.182325
Dammam            2582.109634
Makkah            2355.194209
Qatif             2205.066120
Madinah           1759.142577
Abha              1550.508561
Jubail            1466.625571
Khamis Mushait    1456.247430
Name: price_per_sqm, dtype: float64

In [109]:
df_clean.to_csv("saudi_real_estate_cleaned_2025.csv", index=False, encoding="utf-8-sig")